name: Lean

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: leanprover/lean-action@v1
        with:
          auto-config: false
          use-github-cache: false
      - run: lake update
      - run: lake exe cache get
      - run: lake build
